version: '3.9'

services:

  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - mysql_mysql_local_net

  php-fpm:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    environment:
      - NAMA=value
    networks:
      - mysql_mysql_local_net



networks:
  mysql_mysql_local_net:
    external: true